#!/bin/sh

nm-applet &
nitrogen --restore &
pamac-tray &
dunst &
xautolock -time 5 -locker i3lock-fancy &
compton -cCGb --backend glx --vsync opengl &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xfce4-power-manager &
volumeicon &
[ ! -s ~/.config/mpd/pid ] && mpd &
